language: node_js
node_js:
    - "13"
install:
    - npm install -g firebase-tools elm uglify-js
script:
    - cd public && elm make src/Main.elm --output main.js && uglifyjs main.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | uglifyjs --mangle --output=main.js
after-success:
    - firebase deploy --project echo-bedriftstur-81a2e --token $FIREBASE_TOKEN
